name: Setup Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Composer
      run: |
        sudo apt update
        sudo apt install php composer

        echo this worked and you can view it 
